// Code generated by ent, DO NOT EDIT.

package modelratelimitrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelratelimitrule type in the database.
	Label = "model_rate_limit_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldModelPattern holds the string denoting the model_pattern field in the database.
	FieldModelPattern = "model_pattern"
	// FieldNormalizedPattern holds the string denoting the normalized_pattern field in the database.
	FieldNormalizedPattern = "normalized_pattern"
	// FieldConcurrencyLimit holds the string denoting the concurrency_limit field in the database.
	FieldConcurrencyLimit = "concurrency_limit"
	// FieldRpmLimit holds the string denoting the rpm_limit field in the database.
	FieldRpmLimit = "rpm_limit"
	// FieldTpmLimit holds the string denoting the tpm_limit field in the database.
	FieldTpmLimit = "tpm_limit"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the modelratelimitrule in the database.
	Table = "model_rate_limit_rules"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "model_rate_limit_rules"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for modelratelimitrule fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldModelPattern,
	FieldNormalizedPattern,
	FieldConcurrencyLimit,
	FieldRpmLimit,
	FieldTpmLimit,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ModelPatternValidator is a validator for the "model_pattern" field. It is called by the builders before save.
	ModelPatternValidator func(string) error
	// NormalizedPatternValidator is a validator for the "normalized_pattern" field. It is called by the builders before save.
	NormalizedPatternValidator func(string) error
	// DefaultConcurrencyLimit holds the default value on creation for the "concurrency_limit" field.
	DefaultConcurrencyLimit int
	// ConcurrencyLimitValidator is a validator for the "concurrency_limit" field. It is called by the builders before save.
	ConcurrencyLimitValidator func(int) error
	// DefaultRpmLimit holds the default value on creation for the "rpm_limit" field.
	DefaultRpmLimit int
	// RpmLimitValidator is a validator for the "rpm_limit" field. It is called by the builders before save.
	RpmLimitValidator func(int) error
	// TpmLimitValidator is a validator for the "tpm_limit" field. It is called by the builders before save.
	TpmLimitValidator func(int) error
)

// OrderOption defines the ordering options for the ModelRateLimitRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByModelPattern orders the results by the model_pattern field.
func ByModelPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelPattern, opts...).ToFunc()
}

// ByNormalizedPattern orders the results by the normalized_pattern field.
func ByNormalizedPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNormalizedPattern, opts...).ToFunc()
}

// ByConcurrencyLimit orders the results by the concurrency_limit field.
func ByConcurrencyLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrencyLimit, opts...).ToFunc()
}

// ByRpmLimit orders the results by the rpm_limit field.
func ByRpmLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRpmLimit, opts...).ToFunc()
}

// ByTpmLimit orders the results by the tpm_limit field.
func ByTpmLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTpmLimit, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
