// Code generated by ent, DO NOT EDIT.

package modelratelimitrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldUserID, v))
}

// ModelPattern applies equality check predicate on the "model_pattern" field. It's identical to ModelPatternEQ.
func ModelPattern(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldModelPattern, v))
}

// NormalizedPattern applies equality check predicate on the "normalized_pattern" field. It's identical to NormalizedPatternEQ.
func NormalizedPattern(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldNormalizedPattern, v))
}

// ConcurrencyLimit applies equality check predicate on the "concurrency_limit" field. It's identical to ConcurrencyLimitEQ.
func ConcurrencyLimit(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldConcurrencyLimit, v))
}

// RpmLimit applies equality check predicate on the "rpm_limit" field. It's identical to RpmLimitEQ.
func RpmLimit(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldRpmLimit, v))
}

// TpmLimit applies equality check predicate on the "tpm_limit" field. It's identical to TpmLimitEQ.
func TpmLimit(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldTpmLimit, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotNull(FieldUserID))
}

// ModelPatternEQ applies the EQ predicate on the "model_pattern" field.
func ModelPatternEQ(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldModelPattern, v))
}

// ModelPatternNEQ applies the NEQ predicate on the "model_pattern" field.
func ModelPatternNEQ(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNEQ(FieldModelPattern, v))
}

// ModelPatternIn applies the In predicate on the "model_pattern" field.
func ModelPatternIn(vs ...string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIn(FieldModelPattern, vs...))
}

// ModelPatternNotIn applies the NotIn predicate on the "model_pattern" field.
func ModelPatternNotIn(vs ...string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotIn(FieldModelPattern, vs...))
}

// ModelPatternGT applies the GT predicate on the "model_pattern" field.
func ModelPatternGT(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGT(FieldModelPattern, v))
}

// ModelPatternGTE applies the GTE predicate on the "model_pattern" field.
func ModelPatternGTE(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGTE(FieldModelPattern, v))
}

// ModelPatternLT applies the LT predicate on the "model_pattern" field.
func ModelPatternLT(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLT(FieldModelPattern, v))
}

// ModelPatternLTE applies the LTE predicate on the "model_pattern" field.
func ModelPatternLTE(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLTE(FieldModelPattern, v))
}

// ModelPatternContains applies the Contains predicate on the "model_pattern" field.
func ModelPatternContains(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldContains(FieldModelPattern, v))
}

// ModelPatternHasPrefix applies the HasPrefix predicate on the "model_pattern" field.
func ModelPatternHasPrefix(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldHasPrefix(FieldModelPattern, v))
}

// ModelPatternHasSuffix applies the HasSuffix predicate on the "model_pattern" field.
func ModelPatternHasSuffix(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldHasSuffix(FieldModelPattern, v))
}

// ModelPatternEqualFold applies the EqualFold predicate on the "model_pattern" field.
func ModelPatternEqualFold(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEqualFold(FieldModelPattern, v))
}

// ModelPatternContainsFold applies the ContainsFold predicate on the "model_pattern" field.
func ModelPatternContainsFold(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldContainsFold(FieldModelPattern, v))
}

// NormalizedPatternEQ applies the EQ predicate on the "normalized_pattern" field.
func NormalizedPatternEQ(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldNormalizedPattern, v))
}

// NormalizedPatternNEQ applies the NEQ predicate on the "normalized_pattern" field.
func NormalizedPatternNEQ(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNEQ(FieldNormalizedPattern, v))
}

// NormalizedPatternIn applies the In predicate on the "normalized_pattern" field.
func NormalizedPatternIn(vs ...string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIn(FieldNormalizedPattern, vs...))
}

// NormalizedPatternNotIn applies the NotIn predicate on the "normalized_pattern" field.
func NormalizedPatternNotIn(vs ...string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotIn(FieldNormalizedPattern, vs...))
}

// NormalizedPatternGT applies the GT predicate on the "normalized_pattern" field.
func NormalizedPatternGT(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGT(FieldNormalizedPattern, v))
}

// NormalizedPatternGTE applies the GTE predicate on the "normalized_pattern" field.
func NormalizedPatternGTE(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGTE(FieldNormalizedPattern, v))
}

// NormalizedPatternLT applies the LT predicate on the "normalized_pattern" field.
func NormalizedPatternLT(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLT(FieldNormalizedPattern, v))
}

// NormalizedPatternLTE applies the LTE predicate on the "normalized_pattern" field.
func NormalizedPatternLTE(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLTE(FieldNormalizedPattern, v))
}

// NormalizedPatternContains applies the Contains predicate on the "normalized_pattern" field.
func NormalizedPatternContains(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldContains(FieldNormalizedPattern, v))
}

// NormalizedPatternHasPrefix applies the HasPrefix predicate on the "normalized_pattern" field.
func NormalizedPatternHasPrefix(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldHasPrefix(FieldNormalizedPattern, v))
}

// NormalizedPatternHasSuffix applies the HasSuffix predicate on the "normalized_pattern" field.
func NormalizedPatternHasSuffix(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldHasSuffix(FieldNormalizedPattern, v))
}

// NormalizedPatternEqualFold applies the EqualFold predicate on the "normalized_pattern" field.
func NormalizedPatternEqualFold(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEqualFold(FieldNormalizedPattern, v))
}

// NormalizedPatternContainsFold applies the ContainsFold predicate on the "normalized_pattern" field.
func NormalizedPatternContainsFold(v string) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldContainsFold(FieldNormalizedPattern, v))
}

// ConcurrencyLimitEQ applies the EQ predicate on the "concurrency_limit" field.
func ConcurrencyLimitEQ(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitNEQ applies the NEQ predicate on the "concurrency_limit" field.
func ConcurrencyLimitNEQ(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNEQ(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitIn applies the In predicate on the "concurrency_limit" field.
func ConcurrencyLimitIn(vs ...int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIn(FieldConcurrencyLimit, vs...))
}

// ConcurrencyLimitNotIn applies the NotIn predicate on the "concurrency_limit" field.
func ConcurrencyLimitNotIn(vs ...int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotIn(FieldConcurrencyLimit, vs...))
}

// ConcurrencyLimitGT applies the GT predicate on the "concurrency_limit" field.
func ConcurrencyLimitGT(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGT(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitGTE applies the GTE predicate on the "concurrency_limit" field.
func ConcurrencyLimitGTE(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGTE(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitLT applies the LT predicate on the "concurrency_limit" field.
func ConcurrencyLimitLT(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLT(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitLTE applies the LTE predicate on the "concurrency_limit" field.
func ConcurrencyLimitLTE(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLTE(FieldConcurrencyLimit, v))
}

// RpmLimitEQ applies the EQ predicate on the "rpm_limit" field.
func RpmLimitEQ(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldRpmLimit, v))
}

// RpmLimitNEQ applies the NEQ predicate on the "rpm_limit" field.
func RpmLimitNEQ(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNEQ(FieldRpmLimit, v))
}

// RpmLimitIn applies the In predicate on the "rpm_limit" field.
func RpmLimitIn(vs ...int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIn(FieldRpmLimit, vs...))
}

// RpmLimitNotIn applies the NotIn predicate on the "rpm_limit" field.
func RpmLimitNotIn(vs ...int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotIn(FieldRpmLimit, vs...))
}

// RpmLimitGT applies the GT predicate on the "rpm_limit" field.
func RpmLimitGT(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGT(FieldRpmLimit, v))
}

// RpmLimitGTE applies the GTE predicate on the "rpm_limit" field.
func RpmLimitGTE(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGTE(FieldRpmLimit, v))
}

// RpmLimitLT applies the LT predicate on the "rpm_limit" field.
func RpmLimitLT(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLT(FieldRpmLimit, v))
}

// RpmLimitLTE applies the LTE predicate on the "rpm_limit" field.
func RpmLimitLTE(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLTE(FieldRpmLimit, v))
}

// TpmLimitEQ applies the EQ predicate on the "tpm_limit" field.
func TpmLimitEQ(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldEQ(FieldTpmLimit, v))
}

// TpmLimitNEQ applies the NEQ predicate on the "tpm_limit" field.
func TpmLimitNEQ(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNEQ(FieldTpmLimit, v))
}

// TpmLimitIn applies the In predicate on the "tpm_limit" field.
func TpmLimitIn(vs ...int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIn(FieldTpmLimit, vs...))
}

// TpmLimitNotIn applies the NotIn predicate on the "tpm_limit" field.
func TpmLimitNotIn(vs ...int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotIn(FieldTpmLimit, vs...))
}

// TpmLimitGT applies the GT predicate on the "tpm_limit" field.
func TpmLimitGT(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGT(FieldTpmLimit, v))
}

// TpmLimitGTE applies the GTE predicate on the "tpm_limit" field.
func TpmLimitGTE(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldGTE(FieldTpmLimit, v))
}

// TpmLimitLT applies the LT predicate on the "tpm_limit" field.
func TpmLimitLT(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLT(FieldTpmLimit, v))
}

// TpmLimitLTE applies the LTE predicate on the "tpm_limit" field.
func TpmLimitLTE(v int) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldLTE(FieldTpmLimit, v))
}

// TpmLimitIsNil applies the IsNil predicate on the "tpm_limit" field.
func TpmLimitIsNil() predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldIsNull(FieldTpmLimit))
}

// TpmLimitNotNil applies the NotNil predicate on the "tpm_limit" field.
func TpmLimitNotNil() predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.FieldNotNull(FieldTpmLimit))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelRateLimitRule) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelRateLimitRule) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelRateLimitRule) predicate.ModelRateLimitRule {
	return predicate.ModelRateLimitRule(sql.NotPredicates(p))
}
