// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelratelimitrule"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ModelRateLimitRuleCreate is the builder for creating a ModelRateLimitRule entity.
type ModelRateLimitRuleCreate struct {
	config
	mutation *ModelRateLimitRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelRateLimitRuleCreate) SetCreatedAt(v time.Time) *ModelRateLimitRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelRateLimitRuleCreate) SetNillableCreatedAt(v *time.Time) *ModelRateLimitRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelRateLimitRuleCreate) SetUpdatedAt(v time.Time) *ModelRateLimitRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelRateLimitRuleCreate) SetNillableUpdatedAt(v *time.Time) *ModelRateLimitRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ModelRateLimitRuleCreate) SetUserID(v int64) *ModelRateLimitRuleCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ModelRateLimitRuleCreate) SetNillableUserID(v *int64) *ModelRateLimitRuleCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetModelPattern sets the "model_pattern" field.
func (_c *ModelRateLimitRuleCreate) SetModelPattern(v string) *ModelRateLimitRuleCreate {
	_c.mutation.SetModelPattern(v)
	return _c
}

// SetNormalizedPattern sets the "normalized_pattern" field.
func (_c *ModelRateLimitRuleCreate) SetNormalizedPattern(v string) *ModelRateLimitRuleCreate {
	_c.mutation.SetNormalizedPattern(v)
	return _c
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (_c *ModelRateLimitRuleCreate) SetConcurrencyLimit(v int) *ModelRateLimitRuleCreate {
	_c.mutation.SetConcurrencyLimit(v)
	return _c
}

// SetNillableConcurrencyLimit sets the "concurrency_limit" field if the given value is not nil.
func (_c *ModelRateLimitRuleCreate) SetNillableConcurrencyLimit(v *int) *ModelRateLimitRuleCreate {
	if v != nil {
		_c.SetConcurrencyLimit(*v)
	}
	return _c
}

// SetRpmLimit sets the "rpm_limit" field.
func (_c *ModelRateLimitRuleCreate) SetRpmLimit(v int) *ModelRateLimitRuleCreate {
	_c.mutation.SetRpmLimit(v)
	return _c
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_c *ModelRateLimitRuleCreate) SetNillableRpmLimit(v *int) *ModelRateLimitRuleCreate {
	if v != nil {
		_c.SetRpmLimit(*v)
	}
	return _c
}

// SetTpmLimit sets the "tpm_limit" field.
func (_c *ModelRateLimitRuleCreate) SetTpmLimit(v int) *ModelRateLimitRuleCreate {
	_c.mutation.SetTpmLimit(v)
	return _c
}

// SetNillableTpmLimit sets the "tpm_limit" field if the given value is not nil.
func (_c *ModelRateLimitRuleCreate) SetNillableTpmLimit(v *int) *ModelRateLimitRuleCreate {
	if v != nil {
		_c.SetTpmLimit(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ModelRateLimitRuleCreate) SetUser(v *User) *ModelRateLimitRuleCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ModelRateLimitRuleMutation object of the builder.
func (_c *ModelRateLimitRuleCreate) Mutation() *ModelRateLimitRuleMutation {
	return _c.mutation
}

// Save creates the ModelRateLimitRule in the database.
func (_c *ModelRateLimitRuleCreate) Save(ctx context.Context) (*ModelRateLimitRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelRateLimitRuleCreate) SaveX(ctx context.Context) *ModelRateLimitRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelRateLimitRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelRateLimitRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelRateLimitRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelratelimitrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelratelimitrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ConcurrencyLimit(); !ok {
		v := modelratelimitrule.DefaultConcurrencyLimit
		_c.mutation.SetConcurrencyLimit(v)
	}
	if _, ok := _c.mutation.RpmLimit(); !ok {
		v := modelratelimitrule.DefaultRpmLimit
		_c.mutation.SetRpmLimit(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelRateLimitRuleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelRateLimitRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelRateLimitRule.updated_at"`)}
	}
	if _, ok := _c.mutation.ModelPattern(); !ok {
		return &ValidationError{Name: "model_pattern", err: errors.New(`ent: missing required field "ModelRateLimitRule.model_pattern"`)}
	}
	if v, ok := _c.mutation.ModelPattern(); ok {
		if err := modelratelimitrule.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.model_pattern": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NormalizedPattern(); !ok {
		return &ValidationError{Name: "normalized_pattern", err: errors.New(`ent: missing required field "ModelRateLimitRule.normalized_pattern"`)}
	}
	if v, ok := _c.mutation.NormalizedPattern(); ok {
		if err := modelratelimitrule.NormalizedPatternValidator(v); err != nil {
			return &ValidationError{Name: "normalized_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.normalized_pattern": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConcurrencyLimit(); !ok {
		return &ValidationError{Name: "concurrency_limit", err: errors.New(`ent: missing required field "ModelRateLimitRule.concurrency_limit"`)}
	}
	if v, ok := _c.mutation.ConcurrencyLimit(); ok {
		if err := modelratelimitrule.ConcurrencyLimitValidator(v); err != nil {
			return &ValidationError{Name: "concurrency_limit", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.concurrency_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RpmLimit(); !ok {
		return &ValidationError{Name: "rpm_limit", err: errors.New(`ent: missing required field "ModelRateLimitRule.rpm_limit"`)}
	}
	if v, ok := _c.mutation.RpmLimit(); ok {
		if err := modelratelimitrule.RpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "rpm_limit", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.rpm_limit": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TpmLimit(); ok {
		if err := modelratelimitrule.TpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "tpm_limit", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.tpm_limit": %w`, err)}
		}
	}
	return nil
}

func (_c *ModelRateLimitRuleCreate) sqlSave(ctx context.Context) (*ModelRateLimitRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelRateLimitRuleCreate) createSpec() (*ModelRateLimitRule, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelRateLimitRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelratelimitrule.Table, sqlgraph.NewFieldSpec(modelratelimitrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelratelimitrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelratelimitrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ModelPattern(); ok {
		_spec.SetField(modelratelimitrule.FieldModelPattern, field.TypeString, value)
		_node.ModelPattern = value
	}
	if value, ok := _c.mutation.NormalizedPattern(); ok {
		_spec.SetField(modelratelimitrule.FieldNormalizedPattern, field.TypeString, value)
		_node.NormalizedPattern = value
	}
	if value, ok := _c.mutation.ConcurrencyLimit(); ok {
		_spec.SetField(modelratelimitrule.FieldConcurrencyLimit, field.TypeInt, value)
		_node.ConcurrencyLimit = value
	}
	if value, ok := _c.mutation.RpmLimit(); ok {
		_spec.SetField(modelratelimitrule.FieldRpmLimit, field.TypeInt, value)
		_node.RpmLimit = value
	}
	if value, ok := _c.mutation.TpmLimit(); ok {
		_spec.SetField(modelratelimitrule.FieldTpmLimit, field.TypeInt, value)
		_node.TpmLimit = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelratelimitrule.UserTable,
			Columns: []string{modelratelimitrule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelRateLimitRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelRateLimitRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelRateLimitRuleCreate) OnConflict(opts ...sql.ConflictOption) *ModelRateLimitRuleUpsertOne {
	_c.conflict = opts
	return &ModelRateLimitRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelRateLimitRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelRateLimitRuleCreate) OnConflictColumns(columns ...string) *ModelRateLimitRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelRateLimitRuleUpsertOne{
		create: _c,
	}
}

type (
	// ModelRateLimitRuleUpsertOne is the builder for "upsert"-ing
	//  one ModelRateLimitRule node.
	ModelRateLimitRuleUpsertOne struct {
		create *ModelRateLimitRuleCreate
	}

	// ModelRateLimitRuleUpsert is the "OnConflict" setter.
	ModelRateLimitRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelRateLimitRuleUpsert) SetUpdatedAt(v time.Time) *ModelRateLimitRuleUpsert {
	u.Set(modelratelimitrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsert) UpdateUpdatedAt() *ModelRateLimitRuleUpsert {
	u.SetExcluded(modelratelimitrule.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ModelRateLimitRuleUpsert) SetUserID(v int64) *ModelRateLimitRuleUpsert {
	u.Set(modelratelimitrule.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsert) UpdateUserID() *ModelRateLimitRuleUpsert {
	u.SetExcluded(modelratelimitrule.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *ModelRateLimitRuleUpsert) ClearUserID() *ModelRateLimitRuleUpsert {
	u.SetNull(modelratelimitrule.FieldUserID)
	return u
}

// SetModelPattern sets the "model_pattern" field.
func (u *ModelRateLimitRuleUpsert) SetModelPattern(v string) *ModelRateLimitRuleUpsert {
	u.Set(modelratelimitrule.FieldModelPattern, v)
	return u
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsert) UpdateModelPattern() *ModelRateLimitRuleUpsert {
	u.SetExcluded(modelratelimitrule.FieldModelPattern)
	return u
}

// SetNormalizedPattern sets the "normalized_pattern" field.
func (u *ModelRateLimitRuleUpsert) SetNormalizedPattern(v string) *ModelRateLimitRuleUpsert {
	u.Set(modelratelimitrule.FieldNormalizedPattern, v)
	return u
}

// UpdateNormalizedPattern sets the "normalized_pattern" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsert) UpdateNormalizedPattern() *ModelRateLimitRuleUpsert {
	u.SetExcluded(modelratelimitrule.FieldNormalizedPattern)
	return u
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (u *ModelRateLimitRuleUpsert) SetConcurrencyLimit(v int) *ModelRateLimitRuleUpsert {
	u.Set(modelratelimitrule.FieldConcurrencyLimit, v)
	return u
}

// UpdateConcurrencyLimit sets the "concurrency_limit" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsert) UpdateConcurrencyLimit() *ModelRateLimitRuleUpsert {
	u.SetExcluded(modelratelimitrule.FieldConcurrencyLimit)
	return u
}

// AddConcurrencyLimit adds v to the "concurrency_limit" field.
func (u *ModelRateLimitRuleUpsert) AddConcurrencyLimit(v int) *ModelRateLimitRuleUpsert {
	u.Add(modelratelimitrule.FieldConcurrencyLimit, v)
	return u
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *ModelRateLimitRuleUpsert) SetRpmLimit(v int) *ModelRateLimitRuleUpsert {
	u.Set(modelratelimitrule.FieldRpmLimit, v)
	return u
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsert) UpdateRpmLimit() *ModelRateLimitRuleUpsert {
	u.SetExcluded(modelratelimitrule.FieldRpmLimit)
	return u
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *ModelRateLimitRuleUpsert) AddRpmLimit(v int) *ModelRateLimitRuleUpsert {
	u.Add(modelratelimitrule.FieldRpmLimit, v)
	return u
}

// SetTpmLimit sets the "tpm_limit" field.
func (u *ModelRateLimitRuleUpsert) SetTpmLimit(v int) *ModelRateLimitRuleUpsert {
	u.Set(modelratelimitrule.FieldTpmLimit, v)
	return u
}

// UpdateTpmLimit sets the "tpm_limit" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsert) UpdateTpmLimit() *ModelRateLimitRuleUpsert {
	u.SetExcluded(modelratelimitrule.FieldTpmLimit)
	return u
}

// AddTpmLimit adds v to the "tpm_limit" field.
func (u *ModelRateLimitRuleUpsert) AddTpmLimit(v int) *ModelRateLimitRuleUpsert {
	u.Add(modelratelimitrule.FieldTpmLimit, v)
	return u
}

// ClearTpmLimit clears the value of the "tpm_limit" field.
func (u *ModelRateLimitRuleUpsert) ClearTpmLimit() *ModelRateLimitRuleUpsert {
	u.SetNull(modelratelimitrule.FieldTpmLimit)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelRateLimitRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelRateLimitRuleUpsertOne) UpdateNewValues() *ModelRateLimitRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelratelimitrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelRateLimitRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelRateLimitRuleUpsertOne) Ignore() *ModelRateLimitRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelRateLimitRuleUpsertOne) DoNothing() *ModelRateLimitRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelRateLimitRuleCreate.OnConflict
// documentation for more info.
func (u *ModelRateLimitRuleUpsertOne) Update(set func(*ModelRateLimitRuleUpsert)) *ModelRateLimitRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelRateLimitRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelRateLimitRuleUpsertOne) SetUpdatedAt(v time.Time) *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertOne) UpdateUpdatedAt() *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ModelRateLimitRuleUpsertOne) SetUserID(v int64) *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertOne) UpdateUserID() *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *ModelRateLimitRuleUpsertOne) ClearUserID() *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.ClearUserID()
	})
}

// SetModelPattern sets the "model_pattern" field.
func (u *ModelRateLimitRuleUpsertOne) SetModelPattern(v string) *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertOne) UpdateModelPattern() *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateModelPattern()
	})
}

// SetNormalizedPattern sets the "normalized_pattern" field.
func (u *ModelRateLimitRuleUpsertOne) SetNormalizedPattern(v string) *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetNormalizedPattern(v)
	})
}

// UpdateNormalizedPattern sets the "normalized_pattern" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertOne) UpdateNormalizedPattern() *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateNormalizedPattern()
	})
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (u *ModelRateLimitRuleUpsertOne) SetConcurrencyLimit(v int) *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetConcurrencyLimit(v)
	})
}

// AddConcurrencyLimit adds v to the "concurrency_limit" field.
func (u *ModelRateLimitRuleUpsertOne) AddConcurrencyLimit(v int) *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.AddConcurrencyLimit(v)
	})
}

// UpdateConcurrencyLimit sets the "concurrency_limit" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertOne) UpdateConcurrencyLimit() *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateConcurrencyLimit()
	})
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *ModelRateLimitRuleUpsertOne) SetRpmLimit(v int) *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetRpmLimit(v)
	})
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *ModelRateLimitRuleUpsertOne) AddRpmLimit(v int) *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.AddRpmLimit(v)
	})
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertOne) UpdateRpmLimit() *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateRpmLimit()
	})
}

// SetTpmLimit sets the "tpm_limit" field.
func (u *ModelRateLimitRuleUpsertOne) SetTpmLimit(v int) *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetTpmLimit(v)
	})
}

// AddTpmLimit adds v to the "tpm_limit" field.
func (u *ModelRateLimitRuleUpsertOne) AddTpmLimit(v int) *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.AddTpmLimit(v)
	})
}

// UpdateTpmLimit sets the "tpm_limit" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertOne) UpdateTpmLimit() *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateTpmLimit()
	})
}

// ClearTpmLimit clears the value of the "tpm_limit" field.
func (u *ModelRateLimitRuleUpsertOne) ClearTpmLimit() *ModelRateLimitRuleUpsertOne {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.ClearTpmLimit()
	})
}

// Exec executes the query.
func (u *ModelRateLimitRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelRateLimitRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelRateLimitRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelRateLimitRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelRateLimitRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelRateLimitRuleCreateBulk is the builder for creating many ModelRateLimitRule entities in bulk.
type ModelRateLimitRuleCreateBulk struct {
	config
	err      error
	builders []*ModelRateLimitRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelRateLimitRule entities in the database.
func (_c *ModelRateLimitRuleCreateBulk) Save(ctx context.Context) ([]*ModelRateLimitRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelRateLimitRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelRateLimitRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelRateLimitRuleCreateBulk) SaveX(ctx context.Context) []*ModelRateLimitRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelRateLimitRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelRateLimitRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelRateLimitRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelRateLimitRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelRateLimitRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelRateLimitRuleUpsertBulk {
	_c.conflict = opts
	return &ModelRateLimitRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelRateLimitRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelRateLimitRuleCreateBulk) OnConflictColumns(columns ...string) *ModelRateLimitRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelRateLimitRuleUpsertBulk{
		create: _c,
	}
}

// ModelRateLimitRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelRateLimitRule nodes.
type ModelRateLimitRuleUpsertBulk struct {
	create *ModelRateLimitRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelRateLimitRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelRateLimitRuleUpsertBulk) UpdateNewValues() *ModelRateLimitRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelratelimitrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelRateLimitRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelRateLimitRuleUpsertBulk) Ignore() *ModelRateLimitRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelRateLimitRuleUpsertBulk) DoNothing() *ModelRateLimitRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelRateLimitRuleCreateBulk.OnConflict
// documentation for more info.
func (u *ModelRateLimitRuleUpsertBulk) Update(set func(*ModelRateLimitRuleUpsert)) *ModelRateLimitRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelRateLimitRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelRateLimitRuleUpsertBulk) SetUpdatedAt(v time.Time) *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertBulk) UpdateUpdatedAt() *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ModelRateLimitRuleUpsertBulk) SetUserID(v int64) *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertBulk) UpdateUserID() *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *ModelRateLimitRuleUpsertBulk) ClearUserID() *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.ClearUserID()
	})
}

// SetModelPattern sets the "model_pattern" field.
func (u *ModelRateLimitRuleUpsertBulk) SetModelPattern(v string) *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertBulk) UpdateModelPattern() *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateModelPattern()
	})
}

// SetNormalizedPattern sets the "normalized_pattern" field.
func (u *ModelRateLimitRuleUpsertBulk) SetNormalizedPattern(v string) *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetNormalizedPattern(v)
	})
}

// UpdateNormalizedPattern sets the "normalized_pattern" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertBulk) UpdateNormalizedPattern() *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateNormalizedPattern()
	})
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (u *ModelRateLimitRuleUpsertBulk) SetConcurrencyLimit(v int) *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetConcurrencyLimit(v)
	})
}

// AddConcurrencyLimit adds v to the "concurrency_limit" field.
func (u *ModelRateLimitRuleUpsertBulk) AddConcurrencyLimit(v int) *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.AddConcurrencyLimit(v)
	})
}

// UpdateConcurrencyLimit sets the "concurrency_limit" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertBulk) UpdateConcurrencyLimit() *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateConcurrencyLimit()
	})
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *ModelRateLimitRuleUpsertBulk) SetRpmLimit(v int) *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetRpmLimit(v)
	})
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *ModelRateLimitRuleUpsertBulk) AddRpmLimit(v int) *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.AddRpmLimit(v)
	})
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertBulk) UpdateRpmLimit() *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateRpmLimit()
	})
}

// SetTpmLimit sets the "tpm_limit" field.
func (u *ModelRateLimitRuleUpsertBulk) SetTpmLimit(v int) *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.SetTpmLimit(v)
	})
}

// AddTpmLimit adds v to the "tpm_limit" field.
func (u *ModelRateLimitRuleUpsertBulk) AddTpmLimit(v int) *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.AddTpmLimit(v)
	})
}

// UpdateTpmLimit sets the "tpm_limit" field to the value that was provided on create.
func (u *ModelRateLimitRuleUpsertBulk) UpdateTpmLimit() *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.UpdateTpmLimit()
	})
}

// ClearTpmLimit clears the value of the "tpm_limit" field.
func (u *ModelRateLimitRuleUpsertBulk) ClearTpmLimit() *ModelRateLimitRuleUpsertBulk {
	return u.Update(func(s *ModelRateLimitRuleUpsert) {
		s.ClearTpmLimit()
	})
}

// Exec executes the query.
func (u *ModelRateLimitRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelRateLimitRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelRateLimitRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelRateLimitRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
