// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelratelimitrule"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ModelRateLimitRule is the model entity for the ModelRateLimitRule schema.
type ModelRateLimitRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// ModelPattern holds the value of the "model_pattern" field.
	ModelPattern string `json:"model_pattern,omitempty"`
	// NormalizedPattern holds the value of the "normalized_pattern" field.
	NormalizedPattern string `json:"normalized_pattern,omitempty"`
	// ConcurrencyLimit holds the value of the "concurrency_limit" field.
	ConcurrencyLimit int `json:"concurrency_limit,omitempty"`
	// RpmLimit holds the value of the "rpm_limit" field.
	RpmLimit int `json:"rpm_limit,omitempty"`
	// TpmLimit holds the value of the "tpm_limit" field.
	TpmLimit *int `json:"tpm_limit,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelRateLimitRuleQuery when eager-loading is set.
	Edges        ModelRateLimitRuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelRateLimitRuleEdges holds the relations/edges for other nodes in the graph.
type ModelRateLimitRuleEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelRateLimitRuleEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelRateLimitRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelratelimitrule.FieldID, modelratelimitrule.FieldUserID, modelratelimitrule.FieldConcurrencyLimit, modelratelimitrule.FieldRpmLimit, modelratelimitrule.FieldTpmLimit:
			values[i] = new(sql.NullInt64)
		case modelratelimitrule.FieldModelPattern, modelratelimitrule.FieldNormalizedPattern:
			values[i] = new(sql.NullString)
		case modelratelimitrule.FieldCreatedAt, modelratelimitrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelRateLimitRule fields.
func (_m *ModelRateLimitRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelratelimitrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case modelratelimitrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelratelimitrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelratelimitrule.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case modelratelimitrule.FieldModelPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_pattern", values[i])
			} else if value.Valid {
				_m.ModelPattern = value.String
			}
		case modelratelimitrule.FieldNormalizedPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_pattern", values[i])
			} else if value.Valid {
				_m.NormalizedPattern = value.String
			}
		case modelratelimitrule.FieldConcurrencyLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency_limit", values[i])
			} else if value.Valid {
				_m.ConcurrencyLimit = int(value.Int64)
			}
		case modelratelimitrule.FieldRpmLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rpm_limit", values[i])
			} else if value.Valid {
				_m.RpmLimit = int(value.Int64)
			}
		case modelratelimitrule.FieldTpmLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tpm_limit", values[i])
			} else if value.Valid {
				_m.TpmLimit = new(int)
				*_m.TpmLimit = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelRateLimitRule.
// This includes values selected through modifiers, order, etc.
func (_m *ModelRateLimitRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ModelRateLimitRule entity.
func (_m *ModelRateLimitRule) QueryUser() *UserQuery {
	return NewModelRateLimitRuleClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ModelRateLimitRule.
// Note that you need to call ModelRateLimitRule.Unwrap() before calling this method if this ModelRateLimitRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelRateLimitRule) Update() *ModelRateLimitRuleUpdateOne {
	return NewModelRateLimitRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelRateLimitRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelRateLimitRule) Unwrap() *ModelRateLimitRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelRateLimitRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelRateLimitRule) String() string {
	var builder strings.Builder
	builder.WriteString("ModelRateLimitRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("model_pattern=")
	builder.WriteString(_m.ModelPattern)
	builder.WriteString(", ")
	builder.WriteString("normalized_pattern=")
	builder.WriteString(_m.NormalizedPattern)
	builder.WriteString(", ")
	builder.WriteString("concurrency_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConcurrencyLimit))
	builder.WriteString(", ")
	builder.WriteString("rpm_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.RpmLimit))
	builder.WriteString(", ")
	if v := _m.TpmLimit; v != nil {
		builder.WriteString("tpm_limit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModelRateLimitRules is a parsable slice of ModelRateLimitRule.
type ModelRateLimitRules []*ModelRateLimitRule
