// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelratelimitrule"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ModelRateLimitRuleUpdate is the builder for updating ModelRateLimitRule entities.
type ModelRateLimitRuleUpdate struct {
	config
	hooks    []Hook
	mutation *ModelRateLimitRuleMutation
}

// Where appends a list predicates to the ModelRateLimitRuleUpdate builder.
func (_u *ModelRateLimitRuleUpdate) Where(ps ...predicate.ModelRateLimitRule) *ModelRateLimitRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelRateLimitRuleUpdate) SetUpdatedAt(v time.Time) *ModelRateLimitRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ModelRateLimitRuleUpdate) SetUserID(v int64) *ModelRateLimitRuleUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdate) SetNillableUserID(v *int64) *ModelRateLimitRuleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ModelRateLimitRuleUpdate) ClearUserID() *ModelRateLimitRuleUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *ModelRateLimitRuleUpdate) SetModelPattern(v string) *ModelRateLimitRuleUpdate {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdate) SetNillableModelPattern(v *string) *ModelRateLimitRuleUpdate {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetNormalizedPattern sets the "normalized_pattern" field.
func (_u *ModelRateLimitRuleUpdate) SetNormalizedPattern(v string) *ModelRateLimitRuleUpdate {
	_u.mutation.SetNormalizedPattern(v)
	return _u
}

// SetNillableNormalizedPattern sets the "normalized_pattern" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdate) SetNillableNormalizedPattern(v *string) *ModelRateLimitRuleUpdate {
	if v != nil {
		_u.SetNormalizedPattern(*v)
	}
	return _u
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (_u *ModelRateLimitRuleUpdate) SetConcurrencyLimit(v int) *ModelRateLimitRuleUpdate {
	_u.mutation.ResetConcurrencyLimit()
	_u.mutation.SetConcurrencyLimit(v)
	return _u
}

// SetNillableConcurrencyLimit sets the "concurrency_limit" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdate) SetNillableConcurrencyLimit(v *int) *ModelRateLimitRuleUpdate {
	if v != nil {
		_u.SetConcurrencyLimit(*v)
	}
	return _u
}

// AddConcurrencyLimit adds value to the "concurrency_limit" field.
func (_u *ModelRateLimitRuleUpdate) AddConcurrencyLimit(v int) *ModelRateLimitRuleUpdate {
	_u.mutation.AddConcurrencyLimit(v)
	return _u
}

// SetRpmLimit sets the "rpm_limit" field.
func (_u *ModelRateLimitRuleUpdate) SetRpmLimit(v int) *ModelRateLimitRuleUpdate {
	_u.mutation.ResetRpmLimit()
	_u.mutation.SetRpmLimit(v)
	return _u
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdate) SetNillableRpmLimit(v *int) *ModelRateLimitRuleUpdate {
	if v != nil {
		_u.SetRpmLimit(*v)
	}
	return _u
}

// AddRpmLimit adds value to the "rpm_limit" field.
func (_u *ModelRateLimitRuleUpdate) AddRpmLimit(v int) *ModelRateLimitRuleUpdate {
	_u.mutation.AddRpmLimit(v)
	return _u
}

// SetTpmLimit sets the "tpm_limit" field.
func (_u *ModelRateLimitRuleUpdate) SetTpmLimit(v int) *ModelRateLimitRuleUpdate {
	_u.mutation.ResetTpmLimit()
	_u.mutation.SetTpmLimit(v)
	return _u
}

// SetNillableTpmLimit sets the "tpm_limit" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdate) SetNillableTpmLimit(v *int) *ModelRateLimitRuleUpdate {
	if v != nil {
		_u.SetTpmLimit(*v)
	}
	return _u
}

// AddTpmLimit adds value to the "tpm_limit" field.
func (_u *ModelRateLimitRuleUpdate) AddTpmLimit(v int) *ModelRateLimitRuleUpdate {
	_u.mutation.AddTpmLimit(v)
	return _u
}

// ClearTpmLimit clears the value of the "tpm_limit" field.
func (_u *ModelRateLimitRuleUpdate) ClearTpmLimit() *ModelRateLimitRuleUpdate {
	_u.mutation.ClearTpmLimit()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ModelRateLimitRuleUpdate) SetUser(v *User) *ModelRateLimitRuleUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ModelRateLimitRuleMutation object of the builder.
func (_u *ModelRateLimitRuleUpdate) Mutation() *ModelRateLimitRuleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ModelRateLimitRuleUpdate) ClearUser() *ModelRateLimitRuleUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelRateLimitRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelRateLimitRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelRateLimitRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelRateLimitRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelRateLimitRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelratelimitrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelRateLimitRuleUpdate) check() error {
	if v, ok := _u.mutation.ModelPattern(); ok {
		if err := modelratelimitrule.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.model_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedPattern(); ok {
		if err := modelratelimitrule.NormalizedPatternValidator(v); err != nil {
			return &ValidationError{Name: "normalized_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.normalized_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConcurrencyLimit(); ok {
		if err := modelratelimitrule.ConcurrencyLimitValidator(v); err != nil {
			return &ValidationError{Name: "concurrency_limit", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.concurrency_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RpmLimit(); ok {
		if err := modelratelimitrule.RpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "rpm_limit", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.rpm_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TpmLimit(); ok {
		if err := modelratelimitrule.TpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "tpm_limit", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.tpm_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelRateLimitRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelratelimitrule.Table, modelratelimitrule.Columns, sqlgraph.NewFieldSpec(modelratelimitrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelratelimitrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(modelratelimitrule.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedPattern(); ok {
		_spec.SetField(modelratelimitrule.FieldNormalizedPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConcurrencyLimit(); ok {
		_spec.SetField(modelratelimitrule.FieldConcurrencyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrencyLimit(); ok {
		_spec.AddField(modelratelimitrule.FieldConcurrencyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RpmLimit(); ok {
		_spec.SetField(modelratelimitrule.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmLimit(); ok {
		_spec.AddField(modelratelimitrule.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TpmLimit(); ok {
		_spec.SetField(modelratelimitrule.FieldTpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTpmLimit(); ok {
		_spec.AddField(modelratelimitrule.FieldTpmLimit, field.TypeInt, value)
	}
	if _u.mutation.TpmLimitCleared() {
		_spec.ClearField(modelratelimitrule.FieldTpmLimit, field.TypeInt)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelratelimitrule.UserTable,
			Columns: []string{modelratelimitrule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelratelimitrule.UserTable,
			Columns: []string{modelratelimitrule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelratelimitrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelRateLimitRuleUpdateOne is the builder for updating a single ModelRateLimitRule entity.
type ModelRateLimitRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelRateLimitRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelRateLimitRuleUpdateOne) SetUpdatedAt(v time.Time) *ModelRateLimitRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ModelRateLimitRuleUpdateOne) SetUserID(v int64) *ModelRateLimitRuleUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdateOne) SetNillableUserID(v *int64) *ModelRateLimitRuleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ModelRateLimitRuleUpdateOne) ClearUserID() *ModelRateLimitRuleUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *ModelRateLimitRuleUpdateOne) SetModelPattern(v string) *ModelRateLimitRuleUpdateOne {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdateOne) SetNillableModelPattern(v *string) *ModelRateLimitRuleUpdateOne {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetNormalizedPattern sets the "normalized_pattern" field.
func (_u *ModelRateLimitRuleUpdateOne) SetNormalizedPattern(v string) *ModelRateLimitRuleUpdateOne {
	_u.mutation.SetNormalizedPattern(v)
	return _u
}

// SetNillableNormalizedPattern sets the "normalized_pattern" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdateOne) SetNillableNormalizedPattern(v *string) *ModelRateLimitRuleUpdateOne {
	if v != nil {
		_u.SetNormalizedPattern(*v)
	}
	return _u
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (_u *ModelRateLimitRuleUpdateOne) SetConcurrencyLimit(v int) *ModelRateLimitRuleUpdateOne {
	_u.mutation.ResetConcurrencyLimit()
	_u.mutation.SetConcurrencyLimit(v)
	return _u
}

// SetNillableConcurrencyLimit sets the "concurrency_limit" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdateOne) SetNillableConcurrencyLimit(v *int) *ModelRateLimitRuleUpdateOne {
	if v != nil {
		_u.SetConcurrencyLimit(*v)
	}
	return _u
}

// AddConcurrencyLimit adds value to the "concurrency_limit" field.
func (_u *ModelRateLimitRuleUpdateOne) AddConcurrencyLimit(v int) *ModelRateLimitRuleUpdateOne {
	_u.mutation.AddConcurrencyLimit(v)
	return _u
}

// SetRpmLimit sets the "rpm_limit" field.
func (_u *ModelRateLimitRuleUpdateOne) SetRpmLimit(v int) *ModelRateLimitRuleUpdateOne {
	_u.mutation.ResetRpmLimit()
	_u.mutation.SetRpmLimit(v)
	return _u
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdateOne) SetNillableRpmLimit(v *int) *ModelRateLimitRuleUpdateOne {
	if v != nil {
		_u.SetRpmLimit(*v)
	}
	return _u
}

// AddRpmLimit adds value to the "rpm_limit" field.
func (_u *ModelRateLimitRuleUpdateOne) AddRpmLimit(v int) *ModelRateLimitRuleUpdateOne {
	_u.mutation.AddRpmLimit(v)
	return _u
}

// SetTpmLimit sets the "tpm_limit" field.
func (_u *ModelRateLimitRuleUpdateOne) SetTpmLimit(v int) *ModelRateLimitRuleUpdateOne {
	_u.mutation.ResetTpmLimit()
	_u.mutation.SetTpmLimit(v)
	return _u
}

// SetNillableTpmLimit sets the "tpm_limit" field if the given value is not nil.
func (_u *ModelRateLimitRuleUpdateOne) SetNillableTpmLimit(v *int) *ModelRateLimitRuleUpdateOne {
	if v != nil {
		_u.SetTpmLimit(*v)
	}
	return _u
}

// AddTpmLimit adds value to the "tpm_limit" field.
func (_u *ModelRateLimitRuleUpdateOne) AddTpmLimit(v int) *ModelRateLimitRuleUpdateOne {
	_u.mutation.AddTpmLimit(v)
	return _u
}

// ClearTpmLimit clears the value of the "tpm_limit" field.
func (_u *ModelRateLimitRuleUpdateOne) ClearTpmLimit() *ModelRateLimitRuleUpdateOne {
	_u.mutation.ClearTpmLimit()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ModelRateLimitRuleUpdateOne) SetUser(v *User) *ModelRateLimitRuleUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ModelRateLimitRuleMutation object of the builder.
func (_u *ModelRateLimitRuleUpdateOne) Mutation() *ModelRateLimitRuleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ModelRateLimitRuleUpdateOne) ClearUser() *ModelRateLimitRuleUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ModelRateLimitRuleUpdate builder.
func (_u *ModelRateLimitRuleUpdateOne) Where(ps ...predicate.ModelRateLimitRule) *ModelRateLimitRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelRateLimitRuleUpdateOne) Select(field string, fields ...string) *ModelRateLimitRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelRateLimitRule entity.
func (_u *ModelRateLimitRuleUpdateOne) Save(ctx context.Context) (*ModelRateLimitRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelRateLimitRuleUpdateOne) SaveX(ctx context.Context) *ModelRateLimitRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelRateLimitRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelRateLimitRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelRateLimitRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelratelimitrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelRateLimitRuleUpdateOne) check() error {
	if v, ok := _u.mutation.ModelPattern(); ok {
		if err := modelratelimitrule.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.model_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedPattern(); ok {
		if err := modelratelimitrule.NormalizedPatternValidator(v); err != nil {
			return &ValidationError{Name: "normalized_pattern", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.normalized_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConcurrencyLimit(); ok {
		if err := modelratelimitrule.ConcurrencyLimitValidator(v); err != nil {
			return &ValidationError{Name: "concurrency_limit", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.concurrency_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RpmLimit(); ok {
		if err := modelratelimitrule.RpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "rpm_limit", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.rpm_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TpmLimit(); ok {
		if err := modelratelimitrule.TpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "tpm_limit", err: fmt.Errorf(`ent: validator failed for field "ModelRateLimitRule.tpm_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelRateLimitRuleUpdateOne) sqlSave(ctx context.Context) (_node *ModelRateLimitRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelratelimitrule.Table, modelratelimitrule.Columns, sqlgraph.NewFieldSpec(modelratelimitrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelRateLimitRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelratelimitrule.FieldID)
		for _, f := range fields {
			if !modelratelimitrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelratelimitrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelratelimitrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(modelratelimitrule.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedPattern(); ok {
		_spec.SetField(modelratelimitrule.FieldNormalizedPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConcurrencyLimit(); ok {
		_spec.SetField(modelratelimitrule.FieldConcurrencyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrencyLimit(); ok {
		_spec.AddField(modelratelimitrule.FieldConcurrencyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RpmLimit(); ok {
		_spec.SetField(modelratelimitrule.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmLimit(); ok {
		_spec.AddField(modelratelimitrule.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TpmLimit(); ok {
		_spec.SetField(modelratelimitrule.FieldTpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTpmLimit(); ok {
		_spec.AddField(modelratelimitrule.FieldTpmLimit, field.TypeInt, value)
	}
	if _u.mutation.TpmLimitCleared() {
		_spec.ClearField(modelratelimitrule.FieldTpmLimit, field.TypeInt)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelratelimitrule.UserTable,
			Columns: []string{modelratelimitrule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelratelimitrule.UserTable,
			Columns: []string{modelratelimitrule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ModelRateLimitRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelratelimitrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
